apiVersion: v1
kind: Namespace
metadata:
  name: llama-platform
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-react-frontend
  namespace: llama-platform
  labels:
    app: llama-react-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llama-react-frontend
  template:
    metadata:
      labels:
        app: llama-react-frontend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: react-frontend
          image: 861819669871.dkr.ecr.us-east-1.amazonaws.com/llama-react-frontend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 80
              name: http
              protocol: TCP

          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"

          # Health checks
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: llama-react-frontend
  namespace: llama-platform
  labels:
    app: llama-react-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: llama-react-frontend
